version: '3.9'

services:
  web:
    image: cnblogsflussweb
    build:
      context: .
      dockerfile: src/Cnblogs.Fluss.Web/Dockerfile
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    