version: '3.9'
services:
 web:
   environment:
     - ASPNETCORE_ENVIRONMENT=Docker
     - ASPNETCORE_URLS=http://+:80
   ports:
     - "5106:80"
   volumes:
     - ~/.aspnet/https:/root/.aspnet/https:ro
     - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
 db:
   environment:
     - ACCEPT_EULA=Y
     - MSSQL_SA_PASSWORD=YourStrong-Passw0rd
   ports:
     - "5433:1433"